pub(super) mod cellular;
pub(super) mod cubic;
pub(super) mod fractal;
pub(super) mod generic;
pub(super) mod mixed;
pub(super) mod perlin;
pub(super) mod simplex;
pub(super) mod value;
pub(super) mod white;
